
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_BALL_COLOR_O_DEVICE_ID,
		XPAR_BALL_COLOR_O_BASEADDR,
		XPAR_BALL_COLOR_O_INTERRUPT_PRESENT,
		XPAR_BALL_COLOR_O_IS_DUAL
	},
	{
		XPAR_BALLPOS_XY_DEVICE_ID,
		XPAR_BALLPOS_XY_BASEADDR,
		XPAR_BALLPOS_XY_INTERRUPT_PRESENT,
		XPAR_BALLPOS_XY_IS_DUAL
	},
	{
		XPAR_BATPOS_L_R_DEVICE_ID,
		XPAR_BATPOS_L_R_BASEADDR,
		XPAR_BATPOS_L_R_INTERRUPT_PRESENT,
		XPAR_BATPOS_L_R_IS_DUAL
	},
	{
		XPAR_LEDS_8BIT_DEVICE_ID,
		XPAR_LEDS_8BIT_BASEADDR,
		XPAR_LEDS_8BIT_INTERRUPT_PRESENT,
		XPAR_LEDS_8BIT_IS_DUAL
	},
	{
		XPAR_PUSH_BUTTONS_3BIT_DEVICE_ID,
		XPAR_PUSH_BUTTONS_3BIT_BASEADDR,
		XPAR_PUSH_BUTTONS_3BIT_INTERRUPT_PRESENT,
		XPAR_PUSH_BUTTONS_3BIT_IS_DUAL
	},
	{
		XPAR_SWITCHES_8BIT_DEVICE_ID,
		XPAR_SWITCHES_8BIT_BASEADDR,
		XPAR_SWITCHES_8BIT_INTERRUPT_PRESENT,
		XPAR_SWITCHES_8BIT_IS_DUAL
	}
};


